name: foliage
description: Flutter application for a cryptocurrency wallet, deployed to Android and iOS, using Firebase tooling
publish_to: none
version: 1.0.0
environment:
    sdk: ">=2.18.6 <3.0.0"
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    firebase_core: ^2.4.1
    firebase_auth: ^4.2.5
    cloud_firestore: ^4.3.1
    http: ^0.13.5
    flutter_native_splash: ^2.2.16
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    flutter_launcher_icons: ^0.11.0
flutter:
    uses-material-design: true
    assets:
        - lib/assets/images/
        - lib/assets/vectors/
    fonts:
        - family: SourceSansPro
          fonts:
              - asset: lib/assets/fonts/SourceSansPro-Regular.ttf
              - asset: lib/assets/fonts/SourceSansPro-Italic.ttf
                style: italic
              - asset: lib/assets/fonts/SourceSansPro-SemiBold.ttf
                weight: 600
              - asset: lib/assets/fonts/SourceSansPro-SemiBoldItalic.ttf
                weight: 600
                style: italic
# Adding launcher icons for Android and iOS
flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "lib/assets/images/icon_no_alpha.png"
    min_sdk_android: 26
# Customizing splash screens for Android and iOS
flutter_native_splash:
    color: "#f1f0ea"
    image: "lib/assets/images/icon_alpha.png"
    color_dark: "#272838"
    image_dark: "lib/assets/images/icon_alpha.png"
    android: true
    ios: true
    web: false
    android_12:
        image: "lib/assets/images/icon_alpha.png"
        color: "#f1f0ea"
        image_dark: "lib/assets/images/icon_alpha.png"
        color_dark: "#272838"
    fullscreen: true
