name: crypto_wallet
description: A new Flutter project.
publish_to: none
version: 1.0.0
environment:
    sdk: ">=2.18.6 <3.0.0"
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    firebase_core: ^2.4.1
    firebase_auth: ^4.2.5
    cloud_firestore: ^4.3.1
    http: ^0.13.5
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    flutter_launcher_icons: ^0.11.0
flutter_icons:
    android: launcher_icon
    ios: true
    image_path: lib/assets/icons/icon_white.png
    min_sdk_android: 21
flutter:
    uses-material-design: true
    assets:
        - lib/assets/icons/
        - lib/assets/logos/
        - lib/assets/wordmarks/
    fonts:
        - family: SourceSansPro
          fonts:
              - asset: lib/assets/fonts/SourceSansPro-Regular.ttf
              - asset: lib/assets/fonts/SourceSansPro-Italic.ttf
                style: italic
              - asset: lib/assets/fonts/SourceSansPro-SemiBold.ttf
                weight: 600
              - asset: lib/assets/fonts/SourceSansPro-SemiBoldItalic.ttf
                weight: 600
                style: italic
