name: Android Release
#1. Controls when the workflow will run
on:
    #2. Trigger the workflow on push or pull request for the 'main' branch
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    #3. Allows you to run this workflow manually from the Actions tab of GitHub repo
    workflow_dispatch:

jobs:
    # 4. A single job to build the Android app
    build:
        #5. Contains the type of runner that the job will run on
        runs-on: ubuntu-latest
        #6. Uses steps to represent a sequential list of tasks to be executed
        steps:
            #7. Checks out a copy of your repository on the ubuntu-latest machine
            - uses: actions/checkout@v3
            #8. Sets up the Java version to use for Flutter app build
            - uses: actions/setup-java@v3
              with:
                  distribution: "zulu"
                  java-version: "12.x"
                  cache: "gradle"
            #9. Installs the Flutter SDK
            - uses: subosito/flutter-action@v2
              with:
                  #10. Flutter version to use
                  flutter-version: "3.3.10"
                  channel: "stable"
                  cache: true
            #11. Installs Flutter dependences
            - name: Install dependencies
              run: flutter pub get
            #12. Builds the release APK
            - name: Start release build
              run: flutter build appbundle
